pull user roles authentication login form registration form
Killakan789/testcode pull request #13
Opened 2021-01-24 16:07 UTC by Killakan789

2021-01-24 16:09 UTC, Killakan789 commented on symfony/config/packages/security.yaml
> +        - { path: '/customer/update/{id}', roles: [ IS_AUTHENTICATED_FULLY, ROLE_MANAGER ] }
#7 #8 added and changed access rights in security yaml

2021-01-24 16:09 UTC, Killakan789 commented on symfony/src/Controller/CustomerController.php
> +     * @IsGranted("ROLE_MANAGER")
#7 #8 added and changed access rights in Controller

2021-01-25 11:39 UTC, Ez2815 commented on symfony/src/Controller/CustomerController.php
> +    private $serializer;
also added defining injected services vars #6

2021-02-02 14:12 UTC, avionwd requested changes
Remove obsolete classes that not used to solve the current task (additional authenticators).
How about the functional tests? Do you have a possibility to create tests to cover access settings?

2021-02-02 14:12 UTC, avionwd commented on symfony/config/routes.yaml
> +apiAdd:
Use the `snake_case` naming strategy for route names to follow the defined standards and agreements.

2021-02-02 14:12 UTC, avionwd commented on symfony/migrations/Version20210123180354.php
> +        $this->addSql('ALTER TABLE user DROP api_token');
Created and deleted column in one PR can be omitted as does not exist in the PROD database so only migrations are created and they useless.
The same situation for table `product`.

2021-02-02 14:12 UTC, avionwd commented on symfony/src/Entity/User.php
> +     private $apiToken;
This column was deleted from the database with the migration.

2021-02-02 14:12 UTC, avionwd commented on symfony/config/packages/security.yaml
>          ROLE_ADMIN: [ ROLE_ADMIN ]
Role hierarchy should be used when complex or custom combinations of roles are used. So, no need to define all roles in the config.

2021-02-02 14:12 UTC, avionwd commented on symfony/config/packages/security.yaml
>          - { path: '/customer', roles: [ IS_AUTHENTICATED_FULLY, ROLE_USER ] }
This is no correct use of the access_controll plugin. Read again the [documentation](https://symfony.com/doc/current/security.html#securing-url-patterns-access-control).

It says:

> The most basic way to secure part of your app is to secure an entire URL pattern in security.yaml. For example, to require ROLE_ADMIN for all URLs that start with /admin

So, you should only define the basic rule for API endpoint:
```
- { path: '^/customer', roles: [ IS_AUTHENTICATED_FULLY ] }
```

Role-based access checks already added in the controller action https://github.com/Killakan789/testcode/pull/13/files#diff-2b8ce039958e6c1929ce529f7496743d5dd7267505b862a69c0ab706bb9540e4R37

----
Helpful documentation:
- https://symfony.com/doc/current/security.html#securing-controllers-and-other-code
- https://symfony.com/doc/current/security/access_control.html

2021-02-04 20:36 UTC, Ez2815 commented on symfony/config/routes.yaml
> +apiAdd:
ok, will do

2021-02-04 20:48 UTC, Ez2815 commented on symfony/config/packages/security.yaml
>          ROLE_ADMIN: [ ROLE_ADMIN ]
okay will do.Actually i just tried to set up as much as possible (i wanted to just use the path with regex-"starts from" but thought that this should show that i'm trying to create as much as i can and understand that we may add different roles to access certain pages)will do that

2021-02-17 18:40 UTC, Ez2815 approved these changes

2021-02-17 18:40 UTC, Ez2815 commented on symfony/config/routes.yaml
>    controller: App\Controller\CustomerController::getAll
@avionwd  changed all paths with such name to snakecase names

2021-02-17 18:40 UTC, Ez2815 commented on symfony/config/packages/security.yaml
> +        - { path: '^/customer', roles: [ IS_AUTHENTICATED_FULLY ] }
@avionwd  changed access control construction

2021-03-09 07:43 UTC, merged