test merge and comment assertions
Killakan789/testcode pull request #5
Opened 2021-01-18 16:14 UTC by Killakan789

test merge

2021-01-18 17:03 UTC, avionwd commented on symfony/src/Controller/CustomerController.php
> +            return new Response($jsonContent, Response::HTTP_OK);
Response with errors can't have response code `Response::HTTP_OK` (200 OK). It should be `Response:: HTTP_BAD_REQUEST` (400 Bad Request). Take a look into available response codes: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpFoundation/Response.php#L23

2021-01-18 17:06 UTC, avionwd commented on symfony/src/Dto/CustomerDTO.php
>       * @Assert\Length(min = 8, max = 20, minMessage = "minimal length is 8 numbers in a string", maxMessage = "maximal length is 20 numbers in a string")
nit: message can be omitted as the default message contains all necessary description and also translated into several languages.

2021-01-18 17:11 UTC, avionwd requested changes
Well for issue #1 it's ok to merge this stuff. Fix comments and we can merge changes into the main branch.

2021-01-18 17:11 UTC, avionwd commented on symfony/src/Dto/CustomerDTO.php
>      public $id;
If properties defined as public in the class there is no need to create getters of setter, as you can always get the value from the property itself.

2021-01-18 17:11 UTC, avionwd commented on symfony/src/Controller/CustomerController.php
> +            return new Response($jsonContent, Response::HTTP_OK);
Response with errors can't have response code `Response::HTTP_OK` (200 OK). It should be `Response:: HTTP_BAD_REQUEST` (400 Bad Request). Take a look into available response codes: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/HttpFoundation/Response.php#L23

2021-01-19 12:03 UTC, Killakan789 commented on symfony/src/Dto/CustomerDTO.php
>       */
Testing multiple comment (here you can see validation rules for certain property) #1

2021-01-19 12:03 UTC, Killakan789 commented on symfony/src/Controller/CustomerController.php
> +            return new Response($jsonContent, Response::HTTP_BAD_REQUEST);
changed response to 400 request #1

2021-01-19 12:03 UTC, Killakan789 commented on symfony/src/Dto/CustomerDTO.php
> +     * @Assert\Length(min = 8, max = 20)
disabled message cause actually we have default one and it works as it should (just practiced with asserts)

2021-01-19 12:13 UTC, merged